### PR TITLE
acepta

### PR DESCRIPTION
**Pull request by pvtoari**

### CODE REVIEW

**Review by Kauman189 — COMMENTED** [review]
Sorry I can ' t accept this

**Comment by pvtoari** [comment]
jodete capullo

**Comment by pvtoari** [comment]
$$ cabrooon hueles a caca $$

**Comment by pvtoari** [comment]
jolines

**Comment by Kauman189** [comment]
Dw u can send me more things and ill take a look on it, thank u, a good review its always accepted ;)

**Pull request closed without merging**
